#!/bin/bash
#   Encrypt & Decrypt Files from the Command Line. 
#   Simple wrapper scripts to make encryption even easier.
#   https://github.com/spook/encrypt-decrypt
#
#   Copyright (c) 2018 by Uncle Spook
#
#   MIT License
#
#   Permission is hereby granted, free of charge, to any person obtaining a copy
#   of this software and associated documentation files (the "Software"), to deal
#   in the Software without restriction, including without limitation the rights
#   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#   copies of the Software, and to permit persons to whom the Software is
#   furnished to do so, subject to the following conditions:
#   The above copyright notice and this permission notice shall be included in all
#   copies or substantial portions of the Software.
#   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#   SOFTWARE.

usage () {
    echo "Usage: encrypt [options] files..."
    echo "Encrypt files with a symmetric key (a passphrase)."
    echo ""
    echo "Options:"
    echo "    -h | -?    Display this usage help"
    echo "    -n         Obscure filenames"
    echo "    -p PHRASE  Passphrase - don't use this, it's just for testing!"
    echo "    -v         Verbose mode; give more output"
    exit 0
}

# make default files be {.??,}* to match all files hidden or not?

pwd=""
obscure=false
verbose=false
OPTIND=1         # Reset in case getopts was used earlier
while getopts "h?np:v" opt; do
    case "$opt" in
    h|\?)
        usage
        exit 0
        ;;
    n)  obscure=true
        ;;
    p)  pwd=$OPTARG
        ;;
    v)  verbose=true
        ;;
    esac
done
shift $((OPTIND-1))
[ "${1:-}" = "--" ] && shift

if [ -z "$pwd" ] ; then
    echo -n 'Passphrase: '
    read -s pwd
    echo
    echo -n 'Re-enter: '
    read -s pwd2
    echo
    if [ ! "$pwd" == "$pwd2" ] 
    then
        echo "*** Mismatch"
        exit 1
    fi
fi
if [ -z "$pwd" ] ; then
    echo "*** Passphrase must not be empty"
    exit 22
fi

n=0
for f in "$@"
do 
    if [ ! -f "$f" ]; then
        echo "*** No such file: $f";
        exit 2
    fi
    if [[ "$f" == *".gpg" ]] ; then
        echo "- already encrypted: $f";
    else
        o="$f.gpg"
        if $obscure ; then
            path=$(dirname "$f")    # ${f%/*} fails if no path in name
            name=$(basename "$f")   # ${f##*/} also works
            ba64=`echo "$name" | base64 -w0`
            ba64=${ba64//\//-}      # can't have slashes, make them be dashes
            o="$path/.:.$ba64.gpg"
        fi
        echo "$pwd" | gpg --batch --yes --passphrase-fd 0 -c -o "$o" "$f"
        rm "$f"
        n=$((n+1))
        $verbose && echo "+ encrypted: $f"
    fi
done
echo "$n files encrypted"
exit 0

